/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ldxps;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class EditVend extends javax.swing.JInternalFrame {
    String _cdven;
    
    /**
     * Creates new form EditVend
     */
    public EditVend(String _cdven, JDesktopPane jdpPrincipal) {
        initComponents();
        try{
        this._cdven=_cdven;
        ResultSet rs;
        SimpleDateFormat data = new SimpleDateFormat("yyyy/MM/dd");
        TabelaVendedor editV = new TabelaVendedor();
        editV.Conectar("LDXBC", "root", "root");
        rs = editV.SelectVendedores("CDVEN="+_cdven);
        rs = editV.SelectVendedores("CDCL="+_cdven);
        _dsnome.setText(rs.getString("DSNOME"));
        _cdtab.setText(Integer.toString(rs.getInt("CDTAB")));
        _dtnasc.setText(data.format(rs.getDate("DTNASC")));
        
        
        
        TabelaVendedor tabV = new TabelaVendedor();
        tabV.Conectar("LDXBC", "root", "root");
        
        }catch(ClassNotFoundException|SQLException dx){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        _dsnome = new javax.swing.JTextField();
        _cdtab = new javax.swing.JTextField();
        _dtnasc = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jdpPrincipal.setBackground(new java.awt.Color(250, 250, 250));

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome: ");

        jLabel3.setText("Cód. tabela preços:");

        jLabel4.setText("Data: ");

        _dsnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _dsnomeActionPerformed(evt);
            }
        });

        jButton3.setText("Criar Cliente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jdpPrincipal.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(_dsnome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(_cdtab, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(_dtnasc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(194, 194, 194)
                        .addComponent(_dtnasc, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
                    .addGroup(jdpPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(129, 129, 129)
                        .addComponent(_cdtab))
                    .addGroup(jdpPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(190, 190, 190)
                        .addComponent(_dsnome)))
                .addContainerGap())
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(_dsnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(_cdtab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(_dtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _dsnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__dsnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__dsnomeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CreatClient creatCli = new CreatClient(jdpPrincipal,_cdven);
        this.jdpPrincipal.add(creatCli);
        creatCli.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TabelaVendedor tabV = new TabelaVendedor();
        
        try {
        tabV.Conectar("LDXBC", "root", "root");
        tabV.InsertVendedor(_dsnome.getText(), Integer.parseInt(_cdtab.getText()), Date.valueOf(_dtnasc.getText()));
        tabV.Desconectar();
        } catch (ClassNotFoundException | SQLException ex) {}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{

            TabelaVendedor excC = new TabelaVendedor();
            excC.Conectar("LDXBC", "root", "root");

            if(excC.DeleteVendedor("CDCL="+_cdven))
            JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso");
            else
            JOptionPane.showConfirmDialog(this, "Erro na exclusão");

        } catch(ClassNotFoundException| SQLException cln){}
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _cdtab;
    private javax.swing.JTextField _dsnome;
    private javax.swing.JTextField _dtnasc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JDesktopPane jdpPrincipal;
    // End of variables declaration//GEN-END:variables
}
