/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ldxps;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class EditClient extends javax.swing.JInternalFrame {

    private String _cdcl;
    
    /**
     * Creates new form EditClient
     * (JDesktopPane jdp){
    
        initComponents();
        
        this.jdpPrincipal = jdp;
     */
    public EditClient(String _cdcl, JDesktopPane jdp) {
                
        initComponents();
        this.jdpPrincipal = jdp;
        
        System.out.println("Construtor");
    
        try{
        initComponents();
        tipoPessoa.add(fisica);
        tipoPessoa.add(juridica);
        String tipo_p;
        ResultSet rs,ve;
        
        TabelaCliente editC = new TabelaCliente();
        editC.Conectar("LDXBC", "root", "root");
        rs = editC.SelectClientes("CDCL="+_cdcl);
        _dsnome.setText(rs.getString("dsnome"));
        _dslim.setText(Double.toString(rs.getDouble("limCred")));
        tipo_p=rs.getString("IDTIPO");
        TabelaVendedor tabV = new TabelaVendedor();
        tabV.Conectar("LDXBC", "root", "root");
        /*ve = tabV.SelectVendedores();
        
        do{
            boxVend.addItem(new Vendedor(ve.getString("CDVEN"), ve.getString("DSNOME"), ve.getString("CDTAB"), ve.getString("DTNASC")));
        }while(ve.next());*/
        if(fisica.getActionCommand().equals(tipo_p))
            fisica.setSelected(true);
    
        else
            juridica.setSelected(true);
        ve = tabV.SelectVendedores("CDVEND = " + rs.getLong("CDVEND"));
        Vendedor cliVend = new Vendedor(ve.getString("CDVEN"), ve.getString("DSNOME"), ve.getString("CDTAB"), ve.getString("DTNASC"));
        boxVend.setSelectedItem(cliVend);
           
        this._cdcl=_cdcl;
        
        }catch(ClassNotFoundException|SQLException er){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoPessoa = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jdpPrincipal = new javax.swing.JDesktopPane();
        _dsnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        fisica = new javax.swing.JRadioButton();
        _dslim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        juridica = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boxVend = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jdpPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        _dsnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _dsnomeActionPerformed(evt);
            }
        });

        jLabel4.setText("Limite de crétido:");

        jLabel5.setText("Tipo de Pessoa: ");

        jButton3.setText("Criar Vendedor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        fisica.setText("Física");
        fisica.setToolTipText("");
        fisica.setActionCommand("PF");
        fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fisicaActionPerformed(evt);
            }
        });

        jLabel2.setText("Vendedor:");

        juridica.setText("Juríca");
        juridica.setActionCommand("PJ");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        boxVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxVendActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jdpPrincipal.setLayer(_dsnome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(fisica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(_dslim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(juridica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(boxVend, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
            .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jdpPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jdpPrincipalLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jButton3))
                        .addGroup(jdpPrincipalLayout.createSequentialGroup()
                            .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(110, 110, 110)
                            .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(boxVend, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jdpPrincipalLayout.createSequentialGroup()
                                    .addComponent(fisica)
                                    .addGap(18, 18, 18)
                                    .addComponent(juridica))
                                .addComponent(_dsnome, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                .addComponent(_dslim, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))))
                    .addContainerGap(263, Short.MAX_VALUE)))
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
            .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jdpPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_dsnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGap(27, 27, 27)
                    .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fisica)
                            .addComponent(juridica)))
                    .addGap(24, 24, 24)
                    .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(boxVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(_dslim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(46, 46, 46)
                    .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addContainerGap(80, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{

            TabelaCliente excC = new TabelaCliente();
            excC.Conectar("LDXBC", "root", "root");

            if(excC.DeleteCliente("CDCL="+_cdcl))
            JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso");
            else
            JOptionPane.showConfirmDialog(this, "Erro na exclusão");

        } catch(ClassNotFoundException| SQLException cln){}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            TabelaCliente tabelaC = new TabelaCliente();
            tabelaC.Conectar("LDXBC", "root", "root");
            tabelaC.InsertCliente(_dsnome.getText(), tipoPessoa.getSelection().getActionCommand(), boxVend.getItemAt(boxVend.getSelectedIndex()).getCdven(), Double.parseDouble(_dslim.getText()));
            tabelaC.Desconectar();
        }catch(ClassNotFoundException| SQLException cln){
        cln.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fisicaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CreatVend creatVend = new CreatVend(jdpPrincipal);
        this.jdpPrincipal.add(creatVend);
        creatVend.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void boxVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxVendActionPerformed
        
    }//GEN-LAST:event_boxVendActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        TabelaVendedor tabV = new TabelaVendedor();
        ResultSet ve;
        
        try {
        tabV.Conectar("LDXBC", "root", "root");
        ve = tabV.SelectVendedores();
        while (ve.next()){
            boxVend.addItem(new Vendedor(ve.getString("CDVEN"), ve.getString("DSNOME"), ve.getString("CDTAB"), ve.getString("DTNASC")));
        }
        
        tabV.Desconectar();
        } catch (ClassNotFoundException | SQLException ex) {}
    }//GEN-LAST:event_formInternalFrameActivated

    private void _dsnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__dsnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__dsnomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _dslim;
    private javax.swing.JTextField _dsnome;
    private javax.swing.JComboBox<Vendedor> boxVend;
    private javax.swing.JRadioButton fisica;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JRadioButton juridica;
    private javax.swing.ButtonGroup tipoPessoa;
    // End of variables declaration//GEN-END:variables
}
