/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ldxps;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author gabri
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        TabelaVendedor tabV = new TabelaVendedor();
        ResultSet ve;
        
        vendedores.addItem(new Vendedor("Todos_os_Vendedores", "Todos_os_Vendedores", "", ""));
        try {
        tabV.Conectar("LDXBC", "root", "root");
        ve = tabV.SelectVendedores();
        while (ve.next()){
            vendedores.addItem(new Vendedor(ve.getString("CDVEND"), ve.getString("DSNOME"), ve.getString("CDTAB"), ve.getString("DTNASC")));
        }
        tabV.Desconectar();
        } catch (ClassNotFoundException | SQLException ex) {
        ex.printStackTrace();
        }
    }                   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        vendedores = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        creatrVend = new javax.swing.JMenuItem();
        editVend = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        creatClient = new javax.swing.JMenuItem();
        editClient = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpPrincipal.setBackground(new java.awt.Color(250, 250, 250));

        vendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedoresActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CDCL", "DSNOME", "IDTIPO", "CDVEND", "DSLIM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Vendedor:");

        jLabel2.setText("Cliente:");

        jdpPrincipal.setLayer(vendedores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(vendedores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(530, Short.MAX_VALUE))
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        jMenu1.setText("Vendedor");

        creatrVend.setText("Criar Vendedor");
        creatrVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatrVendActionPerformed(evt);
            }
        });
        jMenu1.add(creatrVend);

        editVend.setText("Editar Vendedor");
        editVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVendActionPerformed(evt);
            }
        });
        jMenu1.add(editVend);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");

        creatClient.setText("Criar Cliente");
        creatClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatClientActionPerformed(evt);
            }
        });
        jMenu2.add(creatClient);

        editClient.setText("Editar Cliente");
        editClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClientActionPerformed(evt);
            }
        });
        jMenu2.add(editClient);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creatClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatClientActionPerformed
                                                 
        CreatClient criaCliente = new CreatClient(jdpPrincipal,"");
        this.jdpPrincipal.add(criaCliente);
      criaCliente.setVisible(true);                                        

    }//GEN-LAST:event_creatClientActionPerformed

    private void editClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClientActionPerformed
        EditClient editC;
        String cdcl;
        
        try {
        cdcl = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
        if(cdcl!=null){
            editC = new EditClient(cdcl, jdpPrincipal);
            this.jdpPrincipal.add(editC);
            editC.setVisible(true);
        }
        } catch (ArrayIndexOutOfBoundsException ex) {}
        
    }//GEN-LAST:event_editClientActionPerformed

    private void creatrVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatrVendActionPerformed
        CreatVend criaVend = new CreatVend(jdpPrincipal);
        this.jdpPrincipal.add(criaVend);
        criaVend.setVisible(true);
    }//GEN-LAST:event_creatrVendActionPerformed

    private void vendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedoresActionPerformed
        TabelaCliente tabC = new TabelaCliente();
        Vendedor selectedVendedor = (Vendedor) vendedores.getSelectedItem();
        ResultSet rs;
        int i = 0;
        
        try {
        tabC.Conectar("LDXBC", "root", "root");
        if (selectedVendedor.getDsnome().equals("Todos_os_Vendedores"))
            rs = tabC.SelectClientes();
        else
            rs = tabC.SelectClientes("CDVEND = '" + selectedVendedor.getCdven() + "'");
        
        while(rs.next()) {
            jTable1.getModel().setValueAt(rs.getString("CDCL"), i, 0);
            jTable1.getModel().setValueAt(rs.getString("DSNOME"), i, 1);
            jTable1.getModel().setValueAt(rs.getString("IDTIPO"), i, 2);
            jTable1.getModel().setValueAt(rs.getString("CDVEND"), i, 3);
            jTable1.getModel().setValueAt(rs.getDouble("DSLIM"), i, 4);
            i++;
        }
        
        tabC.Desconectar();
        } catch (ClassNotFoundException | SQLException ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_vendedoresActionPerformed

    private void editVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVendActionPerformed
        Vendedor vend = (Vendedor) vendedores.getSelectedItem();
        String codVen = vend.getCdven();
        if(codVen!="Todos_os_Clientes"){
            EditVend editVend = new EditVend(vend.getCdven(),jdpPrincipal);
            this.jdpPrincipal.add(editVend);
            editVend.setVisible(true);
        }
    }//GEN-LAST:event_editVendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem creatClient;
    private javax.swing.JMenuItem creatrVend;
    private javax.swing.JMenuItem editClient;
    private javax.swing.JMenuItem editVend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JComboBox<Vendedor> vendedores;
    // End of variables declaration//GEN-END:variables
}
